<a href="https://colab.research.google.com/github/ChonnichaCh/3109/blob/main/3109_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example

## 1.Hello world

In [ ]:
# Never mind this statement, for compatibility reasons
from __future__ import absolute_import, division, print_function, unicode_literals
print("Hello World")

Hello World


## 2.Function, Conditionals, and lteration

In [ ]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("Hello World, x was < 10")
  elif (x < 20):
    print("Hello World, x was >= 10 but < 20")
  else:
    print("Hello World, x was >= 20")
  return x + y
for i in range(8, 25, 5): # i=8, 13, 18, 23 (start, stop, step)
  print("--- Now running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46


In [ ]:
print(HelloWorldXY(1,2))

Hello World, x was < 10
3


## 3.Various kinds of loops starting at () to 2

In [ ]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
  print(i)
print("Iterate over an actual list.")
for i in [0,1]:
  print(i)
print("While works")
i = 0
while i < 2:
  print(i)
  i += 1

Iterate over the items. `range(2)` is like a list [0,1].
0
1
Iterate over an actual list.
0
1
While works
0
1


## 4.Numpy and lists

**Numpy** as np is the fundamental package for scientific computing with Python.

**Lists (Array)** are data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each
element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes,
lists are defined by having values between square brackets [ ].

In [ ]:
sea_creatures = ['shark', 'cuttlefish', 'squid', 'mantis shrimp', 'anemone']

In [ ]:
sea_creatures[0] = 'shark'
sea_creatures[2] = 'squid'
sea_creatures[4] = 'anemone'

In [ ]:
import numpy as np # Make numpy available using np.
# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)
print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [ ]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [ ]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [ ]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.36725405 0.8605195  0.32611184]
 [0.28975139 0.22777183 0.06422646]
 [0.94573007 0.13592289 0.26858896]]


In [ ]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [ ]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


## 5.Colab Specifics: to run commands at the VM's terminal, prefix the line with an exclamation point(!)

In [ ]:
print("\nDoing $ls on filesystem")
!ls -l
!pwd


Doing $ls on filesystem
total 4
drwxr-xr-x 1 root root 4096 Sep  5 17:47 sample_data
/content


In [ ]:
print("Install numpy") # Just for test, numpy is actually preinstalled in all Colab instancs
!pip install numpy

Install numpy


# Exercise

## 1.Colab: Create a code cell underneath this text cell and add code to:

- List the path of the current directory(pwd)
- Go to / (cd) and list the content(ls-l)

## 2.Python lists without Numpy: Print the second item in the fruits list:

## 3.Change the value from "apple" to "kiwi", in the fruits list:

## 4.Use the append method to add "orange" to the fruits list:

## 5.Use the insert method to add "lemon" as the second item in the fruits list:

## 6.Use the remove method to delete "banana" from the fruits list:

## 7.Python If...Else: Print "Hello World" if a is greater than b:

## 8.Print "Hello World" if a is not equal to b:

## 9.Print "Yes" if a is equal to b, otherwise print "No":

## 10.Print "1" if a is equal to b, print "2" if a is greater than b, otherwise print "3":

## 11.Print "Hello" if either a is equal to b, and c is equal to d:

## 12.Print "Hello" if either a is equal to b, or c is equal to d:

## 13.Python Loops: Print i as long as i is less then 6:

## 14.From #13 stop the loop if i is 3: